services:
  - type: worker
    name: welcome-discord-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false   # You will add this in Render Dashboard
